name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Pull and Push Docker Images
    runs-on: ubuntu-latest
    steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build and push image Aliyun
      run: |
        set -euxo pipefail

        echo "Logging in to Aliyun Docker registry"
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

        echo "Processing images to check for duplicates"
        declare -A duplicate_images
        declare -A temp_map
        while IFS= read -r line; do
            echo "Read line: $line"
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                echo "Skipping comment line: $line"
                continue
            fi

            image=$(echo "$line" | awk '{print $NF}')
            image="${image%%@*}"
            echo "Processed image: $image"

            image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
            echo "Image name and tag: $image_name_tag"

            name_space=$(echo "$image" | awk -F'/' '{if (NF==3) print $2; else if (NF==2) print $1; else print ""}')
            echo "Namespace: $name_space"
            name_space="${name_space}_"

            image_name=$(echo "$image_name_tag" | awk -F':' '{print $1}')
            echo "Image name: $image_name"

            if [[ -n "${temp_map[$image_name]}" ]]; then
                if [[ "${temp_map[$image_name]}" != "$name_space" ]]; then
                    echo "Duplicate image name detected: $image_name"
                    duplicate_images[$image_name]="true"
                fi
            else
                temp_map[$image_name]=$name_space
            fi
        done < images.txt

        echo "Starting image pull, tag, and push process"
        while IFS= read -r line; do
            echo "Read line: $line"
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                echo "Skipping comment line: $line"
                continue
            fi

            echo "Pulling image: $line"
            docker pull "$line"

            platform=$(echo "$line" | awk -F'--platform[ =]' '{if (NF>1) print $2}' | awk '{print $1}')
            echo "Platform: $platform"
            if [ -z "$platform" ]; then
                platform_prefix=""
            else
                platform_prefix="${platform//\//_}_"
            fi
            echo "Platform prefix: $platform_prefix"

            image=$(echo "$line" | awk '{print $NF}')
            image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
            name_space=$(echo "$image" | awk -F'/' '{if (NF==3) print $2; else if (NF==2) print $1; else print ""}')
            image_name=$(echo "$image_name_tag" | awk -F':' '{print $1}')

            echo "Processing image: $image_name_tag"
            name_space_prefix=""
            if [[ -n "${duplicate_images[$image_name]}" ]]; then
                if [[ -n "${name_space}" ]]; then
                    name_space_prefix="${name_space}_"
                fi
            fi

            image_name_tag="${image_name_tag%%@*}"
            new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$platform_prefix$name_space_prefix$image_name_tag"
            echo "Tagging image $image as $new_image"
            docker tag "$image" "$new_image"

            echo "Pushing image $new_image"
            docker push "$new_image"
        done < images.txt
